// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestOdataProblem.Db;

namespace TestOdataProblem.Migrations
{
    [DbContext(typeof(TestOdataContext))]
    partial class TestOdataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("TestOdataProblem.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("26f5d47a-0088-4c4b-9bfb-a893cfde68ea"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Smith",
                            OfficeId = new Guid("3416c9e4-4c1c-4122-bf8a-8bb6428238f0")
                        },
                        new
                        {
                            Id = new Guid("5f324e14-542c-4a40-a4b8-8acca5c0dce6"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            OfficeId = new Guid("3416c9e4-4c1c-4122-bf8a-8bb6428238f0")
                        },
                        new
                        {
                            Id = new Guid("6d96cbd4-61b2-4786-b9c4-29191c61e41a"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Vic Down",
                            OfficeId = new Guid("3416c9e4-4c1c-4122-bf8a-8bb6428238f0")
                        },
                        new
                        {
                            Id = new Guid("ef90ef76-7751-41f2-9dfc-887c291bd2f9"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amanda Tulip",
                            OfficeId = new Guid("3f22c7dd-4b17-403e-bbb5-4d8c30520cb7")
                        },
                        new
                        {
                            Id = new Guid("9b3592ae-ab5d-45d3-a153-f6d93a870c9c"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane S",
                            OfficeId = new Guid("c21fa9a0-98f2-4453-aa1f-7906b7d297dd")
                        },
                        new
                        {
                            Id = new Guid("aecfa712-1d14-45ef-8150-9db3ce550c4e"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Green",
                            OfficeId = new Guid("c21fa9a0-98f2-4453-aa1f-7906b7d297dd")
                        },
                        new
                        {
                            Id = new Guid("df4fe7a8-c754-473a-aaf1-13ebcbf8be90"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ben Foss",
                            OfficeId = new Guid("3498634e-b8ae-4c8e-b699-0fbafc7d8729")
                        },
                        new
                        {
                            Id = new Guid("7925c62d-1b8d-4009-8559-15e9ed43b46a"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Milton P Smith",
                            OfficeId = new Guid("8a01633a-fdb0-44ab-bee1-ca8ccb2ed0de")
                        },
                        new
                        {
                            Id = new Guid("803fc464-1ecb-40f2-b3a4-54396f5c38ba"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dewey K Smith",
                            OfficeId = new Guid("8a01633a-fdb0-44ab-bee1-ca8ccb2ed0de")
                        },
                        new
                        {
                            Id = new Guid("b75e73ef-bac5-475b-9f06-cbf82e8f344c"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Harrison F Johnson",
                            OfficeId = new Guid("096904e4-bab9-4f1a-b7f3-27524e9e658b")
                        },
                        new
                        {
                            Id = new Guid("2682660b-e6f7-452d-8677-c70c75d6c13d"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brian K Johnson",
                            OfficeId = new Guid("096904e4-bab9-4f1a-b7f3-27524e9e658b")
                        },
                        new
                        {
                            Id = new Guid("7036fab9-6196-4b14-be8f-39012be8109d"),
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amber Smith",
                            OfficeId = new Guid("4200b0ae-de2b-4ebb-8a25-d8227431d921")
                        });
                });

            modelBuilder.Entity("TestOdataProblem.Models.Office", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3416c9e4-4c1c-4122-bf8a-8bb6428238f0"),
                            Active = true,
                            AddressLine = "58 Fair St",
                            City = "Kingston",
                            ZipCode = "12401"
                        },
                        new
                        {
                            Id = new Guid("3f22c7dd-4b17-403e-bbb5-4d8c30520cb7"),
                            Active = true,
                            AddressLine = "426 Brazos Hill Ln",
                            City = "Sealy",
                            ZipCode = "77474"
                        },
                        new
                        {
                            Id = new Guid("3498634e-b8ae-4c8e-b699-0fbafc7d8729"),
                            Active = true,
                            AddressLine = "78 College Ave",
                            City = "New Brunswick",
                            ZipCode = "08901"
                        },
                        new
                        {
                            Id = new Guid("c21fa9a0-98f2-4453-aa1f-7906b7d297dd"),
                            Active = true,
                            AddressLine = "178 Chandlers Ferry Rd",
                            City = "Hartwell",
                            ZipCode = "30643"
                        },
                        new
                        {
                            Id = new Guid("d6a97b73-e935-41e4-88df-9b735bce29b5"),
                            Active = true,
                            AddressLine = "110 Popular St",
                            City = "Chunky",
                            ZipCode = "39323"
                        },
                        new
                        {
                            Id = new Guid("8a01633a-fdb0-44ab-bee1-ca8ccb2ed0de"),
                            Active = true,
                            AddressLine = "111 Yale Rd",
                            City = "Audubon",
                            ZipCode = "08106"
                        },
                        new
                        {
                            Id = new Guid("f36f5352-ed1d-495d-8b20-a8ddfacd792d"),
                            Active = true,
                            AddressLine = "173 N Wantagh Ave",
                            City = "Levittown",
                            ZipCode = "11756"
                        },
                        new
                        {
                            Id = new Guid("096904e4-bab9-4f1a-b7f3-27524e9e658b"),
                            Active = true,
                            AddressLine = "248 Leighton Ave",
                            City = "Red Bank",
                            ZipCode = "07701"
                        },
                        new
                        {
                            Id = new Guid("4200b0ae-de2b-4ebb-8a25-d8227431d921"),
                            Active = true,
                            AddressLine = "837 Estancia Way",
                            City = "San Rafael",
                            ZipCode = "94903"
                        },
                        new
                        {
                            Id = new Guid("1cc41eb5-7839-46e8-8efa-b1cfd2721a62"),
                            Active = true,
                            AddressLine = "42 Meadowbrook Park Dr",
                            City = "Kernersville",
                            ZipCode = "27284"
                        },
                        new
                        {
                            Id = new Guid("0d1259c5-f06b-4e86-b7d0-5f56bfa5c70b"),
                            Active = true,
                            AddressLine = "899  Randall Drive",
                            City = "Hillo",
                            ZipCode = "96720"
                        },
                        new
                        {
                            Id = new Guid("75ae4ecb-50c0-44bb-abd8-c6020ada346c"),
                            Active = true,
                            AddressLine = "303  Gerald L. Bates Drive",
                            City = "LYNDON",
                            ZipCode = "66451"
                        },
                        new
                        {
                            Id = new Guid("3123333b-4ac5-4d1b-9047-7881d060df68"),
                            Active = true,
                            AddressLine = "18 Fair St",
                            City = "Kingston",
                            ZipCode = "12401"
                        },
                        new
                        {
                            Id = new Guid("c563789f-af45-4946-a2ab-46dab5b7856d"),
                            Active = true,
                            AddressLine = "3440  Indiana Avenue",
                            City = "Kingston",
                            ZipCode = "12401"
                        },
                        new
                        {
                            Id = new Guid("691cc6f4-76af-4df6-99dc-34dfbc93ab6e"),
                            Active = false,
                            AddressLine = "108 Fair St",
                            City = "Kingston",
                            ZipCode = "12401"
                        });
                });

            modelBuilder.Entity("TestOdataProblem.Models.Employee", b =>
                {
                    b.HasOne("TestOdataProblem.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("TestOdataProblem.Models.Office", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
